---
- name: deploy | prerequisites
  hosts: all
  become: yes
  become_user: comicbookcore
  vars:
    site_dir: /home/comicbookcore/www/comicbookcore.com
  tasks:
    - name: create site folder (if needed)
      file:
        path: "{{ site_dir }}"
        state: directory
    - name: clone repo
      git:
        repo: "https://github.com/delameko/comicbookcore.git"
        dest: "{{ site_dir }}"
